### ISSUE TITLE
The reference to zip is the PKWARE note, not the ISO spec

### ISSUE THREAD

**Issue by llemeurfr** [w3c/lpf#12]
The form [[zip]] in the spec links to the PKWARE note. I think this is a reference configurerd by the W3C. 
I could be good to have also a reference to https://www.iso.org/standard/60101.html, even if this spec cannot be read freely

**Comment by iherman** [comment]
@llemeurfr it is possible, in respec, to add one's own bibliography entry and use those, too. See the usage of biblio.js in the manifest spec.

(I agree that _adding_ the ZIP ISO document makes sense.)

**Comment by llemeurfr** [comment]
In https://github.com/w3c/respec/wiki/localBiblio, the example shows a status: I found the list in https://github.com/w3c/respec/wiki/specStatus. There is no valid value for an International Standard which W3C did not publish. W3C advice welcome.

**Comment by iherman** [comment]
@llemeurfr I am not sure I understand the problem... Look at the way extra references are added to the local biblio file for the publication manifest. The same mechanism should work here, too.

I can look at this tomorrow, I have been on the road today...

**Comment by mattgarrish** [comment]
The status doesn't have to be one of those codes. You can use them if they're relevant, but you can also just write in whatever status is applicable. For ISO docs, you can just use:

```
status: "International Standard"
```

See https://github.com/tobie/specref/blob/master/refs/biblio.json#L1675

**Comment by llemeurfr** [comment]
Fixed by 3cf1afda7892e9d1719eb9511b55da36eb11201e
