### ISSUE TITLE
Document reference in the Media type section

### ISSUE THREAD

**Issue by iherman** [w3c/lpf#14]
There is a reference to the editors' draft (under 'Published specification'). That should be https://www.w3.org/TR/lpf

**Comment by iherman** [comment]
Note to ourselves: once published, we will have to register the media type. @llemeurfr can you ping me when the time comes?

**Comment by llemeurfr** [comment]
True. I was hesitating including a link that is 404 for now. But after all, let's do it now before release.

**Comment by llemeurfr** [comment]
Fixed by 8eebb7f3fd6f111e1b1d9758de87863e07583673
