### ISSUE TITLE
Naming and scope concern

### ISSUE THREAD

**Issue by larscwallin** [w3c/lpf#3]
I am bit concerned by the generic naming of the format. "Lightweight Packaging Format" does not make it clear that it is specifically meant to package Web Publications.
Also the wording in the note that limits the LPF to only package Web Publications is problematic since we will need to package other types of resources as well such as Web Annotations, Synchronized Media etc.

**Comment by llemeurfr** [comment]
Hi Lars, it packages a "Publication Manifest" with the "inner resources" of a publication. the "Web" term has been removed from the Publication Manifest spec by the WG. 

I agree that a Package will contain Synchronized Media structures, which will be  stored in the Package in any folder and referenced in the Publication Manifest without needing specific rules.

The Package spec may easily be extended to also contain personal Web Annotations. I agree that it would be useful (putting the fork and the knife side by side) but this may be an issue for some people in the WG (it is a personalization of a published asset). For generally the standardization of the use of sharable Web Annotations as a complement for Web Publications should be discussed at a latter stage by the WG, it's a fascinating subject.

The "Lightweight Packaging Format" name was accepted by the WG some months ago, it's already 3 words, adding something about "Publications" (e.g. "Lightweight Publication Packaging Format" or "Lightweight Packaging Format for Publications") would be more complete BUT also more difficult to use. But I'll let others give their opinion.

**Comment by larscwallin** [comment]
Thanks for the reply Laurent. Removing the "root context" from the name of what is to become a published W3C document, just so that a abbreviation looks nice, is so against my principles that my head hurts.
My suggestion would be to remove "Lightweight" as it is redundant in comparison with the need to clarify the relation with the publication manifest.

**Comment by larscwallin** [comment]
When it comes to the question of "scope" I am going to contradict my above comment a bit. I would actually appreciate a true "Lightweight Packaging Format" that depends on a generic manifest schema that can be extended to handle all sorts of manifest types, including the Publication Manifest.
If we could make this small change to the document LPF would actually fit the bill.

**Comment by larscwallin** [comment]
PS. Sorry for being very square about naming conventions etc. It is dear to my heart 😉

**Comment by llemeurfr** [comment]
relates to https://github.com/w3c/pwpub/issues/29
and https://github.com/w3c/pwpub/commit/1a0cbb5c312288fb3aa9f00caa2afa9fc6820c44#diff-4d922639b43ce326710e8281da869e41.

**Comment by llemeurfr** [comment]
Decision to keep the current name was taken by the WG in November 2019.
