### ISSUE TITLE
dom reference?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/lpf#6]
Where is that informative reference coming from? I don't see anything in the spec.

**Comment by mattgarrish** [comment]
Found it in 2.4. There's a link in step 6./3. without a reference after.

**Comment by llemeurfr** [comment]
It comes from ```a data-cite="!dom#concept-child-text-content">```. Is there any issue with it?

**Comment by iherman** [comment]
Ah, it seems that respec generates an entry to such a reference even if it is not called out explicitly by a [[dom]] statement. I think that is actually a good thing, we should leave it as is.

**Comment by llemeurfr** [comment]
I agree to close it.
