### ISSUE TITLE
intro informative

### ISSUE THREAD

**Issue by mattgarrish** [w3c/lpf#7]
Since we just went through this with pub-manifest, it's probably better to move the terminology out of the intro. The intro paras can then be marked informative.

**Comment by iherman** [comment]
@mattgarrish is that really relevant? This is a Note, the whole document is informative...

**Comment by mattgarrish** [comment]
> is that really relevant? This is a Note, the whole document is informative...

You tell me... :)

My impression of W3C has been that publishing as a note is just that the document has no formal standing. I'd assumed it was still relevant within the document to identify what you believe to be normative/informative, etc.

**Comment by iherman** [comment]
I do not think that a note can have, strictly speaking, normative references. I would not be surprised if respec refused to generate those (but I do not know).

That being said, you may be right that marking sections as 'informative' does not do any harm (and that should be done consistently), but some aspects (like the references) may not work.

**Comment by mattgarrish** [comment]
Ya, my only frame of reference is wpub. We published that with all the normative/informative prose intact, so I'm just assuming we do the same here.
