### ISSUE TITLE
explain lightweight

### ISSUE THREAD

**Issue by mattgarrish** [w3c/lpf#8]
As I mentioned on the call, some explanation of "lightweight" would help to avoid any general confusion. At least as I understand the rationale for it, you might just add a paragraph like the following to start the intro:

"The Lightweight Packaging Format provides a means of packaging digital publication profiles of the Web Publication specification. This format is based on the [OCF] format widely used in publishing to package EPUB publications, but in a more lightweight way - it removes many of the cumbersome rules and restrictions imposed by that format to make packaging and processing simpler."

**Comment by dauwhe** [comment]
> "The Lightweight Packaging Format provides a means of packaging digital publication profiles of the Web Publication specification. This format is based on the [OCF] format widely used in publishing to package EPUB publications, but in a more lightweight way - it removes many of the cumbersome rules and restrictions imposed by that format to make packaging and processing simpler."

I'd maybe go in the other direction, and try to say it's just zip with a simple way of finding the necessary files, and so as simple as possible. "Lighter than OCF" is like saying something is lighter than a whale.

**Comment by mattgarrish** [comment]
> "Lighter than OCF" is like saying something is lighter than a whale.

Ya, but it's not really making zip any lighter.

**Comment by mattgarrish** [comment]
But, to be clear, I don't really care which we we go so long as there's some rationale for the word. That way we don't invite any questions of what "lightweight" means.

**Comment by llemeurfr** [comment]
proposal in the new version of the introduction:

> This specification is based on proven technologies and allows digital publications to be packaged in an easy way, hence the term "lightweight" used in its name.
